elasticsearch:
  build: elasticsearch/
  environment:
    - ES_HEAP_SIZE=1024m
  command: elasticsearch -Des.network.host=0.0.0.0
  volumes: 
    - /etc/localtime:/etc/localtime
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - /etc/localtime:/etc/localtime
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  ports:
    - "5140:5140/udp"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
    - /etc/localtime:/etc/localtime
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  ports:
    - "5601:5601"
  links:
    - elasticsearch
